// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.2
// source: github.com/gritcli/grit/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuggestRepoFilter int32

const (
	SuggestRepoFilter_SUGGEST_ANY         SuggestRepoFilter = 0
	SuggestRepoFilter_SUGGEST_LOCAL_ONLY  SuggestRepoFilter = 1
	SuggestRepoFilter_SUGGEST_REMOTE_ONLY SuggestRepoFilter = 2
)

// Enum value maps for SuggestRepoFilter.
var (
	SuggestRepoFilter_name = map[int32]string{
		0: "SUGGEST_ANY",
		1: "SUGGEST_LOCAL_ONLY",
		2: "SUGGEST_REMOTE_ONLY",
	}
	SuggestRepoFilter_value = map[string]int32{
		"SUGGEST_ANY":         0,
		"SUGGEST_LOCAL_ONLY":  1,
		"SUGGEST_REMOTE_ONLY": 2,
	}
)

func (x SuggestRepoFilter) Enum() *SuggestRepoFilter {
	p := new(SuggestRepoFilter)
	*p = x
	return p
}

func (x SuggestRepoFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuggestRepoFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_gritcli_grit_api_api_proto_enumTypes[0].Descriptor()
}

func (SuggestRepoFilter) Type() protoreflect.EnumType {
	return &file_github_com_gritcli_grit_api_api_proto_enumTypes[0]
}

func (x SuggestRepoFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuggestRepoFilter.Descriptor instead.
func (SuggestRepoFilter) EnumDescriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{0}
}

type ListSourcesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{0}
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []*Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description  string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status       string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	BaseCloneDir string `protobuf:"bytes,4,opt,name=base_clone_dir,json=baseCloneDir,proto3" json:"base_clone_dir,omitempty"`
}

func (x *Source) Reset() {
	*x = Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Source) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Source) GetBaseCloneDir() string {
	if x != nil {
		return x.BaseCloneDir
	}
	return ""
}

type RemoteRepo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source      string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	WebUrl      string `protobuf:"bytes,5,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
}

func (x *RemoteRepo) Reset() {
	*x = RemoteRepo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteRepo) ProtoMessage() {}

func (x *RemoteRepo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteRepo.ProtoReflect.Descriptor instead.
func (*RemoteRepo) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteRepo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoteRepo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RemoteRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteRepo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RemoteRepo) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

type LocalRepo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteRepo       *RemoteRepo `protobuf:"bytes,1,opt,name=remote_repo,json=remoteRepo,proto3" json:"remote_repo,omitempty"`
	AbsoluteCloneDir string      `protobuf:"bytes,2,opt,name=absolute_clone_dir,json=absoluteCloneDir,proto3" json:"absolute_clone_dir,omitempty"`
}

func (x *LocalRepo) Reset() {
	*x = LocalRepo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalRepo) ProtoMessage() {}

func (x *LocalRepo) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalRepo.ProtoReflect.Descriptor instead.
func (*LocalRepo) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *LocalRepo) GetRemoteRepo() *RemoteRepo {
	if x != nil {
		return x.RemoteRepo
	}
	return nil
}

func (x *LocalRepo) GetAbsoluteCloneDir() string {
	if x != nil {
		return x.AbsoluteCloneDir
	}
	return ""
}

type ClientOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptureDebugLog bool `protobuf:"varint,1,opt,name=capture_debug_log,json=captureDebugLog,proto3" json:"capture_debug_log,omitempty"`
}

func (x *ClientOptions) Reset() {
	*x = ClientOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOptions) ProtoMessage() {}

func (x *ClientOptions) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOptions.ProtoReflect.Descriptor instead.
func (*ClientOptions) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{5}
}

func (x *ClientOptions) GetCaptureDebugLog() bool {
	if x != nil {
		return x.CaptureDebugLog
	}
	return false
}

type ClientOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsDebug bool   `protobuf:"varint,2,opt,name=is_debug,json=isDebug,proto3" json:"is_debug,omitempty"`
}

func (x *ClientOutput) Reset() {
	*x = ClientOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOutput) ProtoMessage() {}

func (x *ClientOutput) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOutput.ProtoReflect.Descriptor instead.
func (*ClientOutput) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{6}
}

func (x *ClientOutput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientOutput) GetIsDebug() bool {
	if x != nil {
		return x.IsDebug
	}
	return false
}

type ResolveLocalRepoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientOptions *ClientOptions `protobuf:"bytes,1,opt,name=client_options,json=clientOptions,proto3" json:"client_options,omitempty"`
	Query         string         `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ResolveLocalRepoRequest) Reset() {
	*x = ResolveLocalRepoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveLocalRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLocalRepoRequest) ProtoMessage() {}

func (x *ResolveLocalRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLocalRepoRequest.ProtoReflect.Descriptor instead.
func (*ResolveLocalRepoRequest) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveLocalRepoRequest) GetClientOptions() *ClientOptions {
	if x != nil {
		return x.ClientOptions
	}
	return nil
}

func (x *ResolveLocalRepoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResolveLocalRepoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*ResolveLocalRepoResponse_Output
	//	*ResolveLocalRepoResponse_LocalRepo
	Response isResolveLocalRepoResponse_Response `protobuf_oneof:"response"`
}

func (x *ResolveLocalRepoResponse) Reset() {
	*x = ResolveLocalRepoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveLocalRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveLocalRepoResponse) ProtoMessage() {}

func (x *ResolveLocalRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveLocalRepoResponse.ProtoReflect.Descriptor instead.
func (*ResolveLocalRepoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{8}
}

func (m *ResolveLocalRepoResponse) GetResponse() isResolveLocalRepoResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ResolveLocalRepoResponse) GetOutput() *ClientOutput {
	if x, ok := x.GetResponse().(*ResolveLocalRepoResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *ResolveLocalRepoResponse) GetLocalRepo() *LocalRepo {
	if x, ok := x.GetResponse().(*ResolveLocalRepoResponse_LocalRepo); ok {
		return x.LocalRepo
	}
	return nil
}

type isResolveLocalRepoResponse_Response interface {
	isResolveLocalRepoResponse_Response()
}

type ResolveLocalRepoResponse_Output struct {
	Output *ClientOutput `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ResolveLocalRepoResponse_LocalRepo struct {
	LocalRepo *LocalRepo `protobuf:"bytes,2,opt,name=local_repo,json=localRepo,proto3,oneof"`
}

func (*ResolveLocalRepoResponse_Output) isResolveLocalRepoResponse_Response() {}

func (*ResolveLocalRepoResponse_LocalRepo) isResolveLocalRepoResponse_Response() {}

type ResolveRemoteRepoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientOptions *ClientOptions `protobuf:"bytes,1,opt,name=client_options,json=clientOptions,proto3" json:"client_options,omitempty"`
	Query         string         `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ResolveRemoteRepoRequest) Reset() {
	*x = ResolveRemoteRepoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRemoteRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRemoteRepoRequest) ProtoMessage() {}

func (x *ResolveRemoteRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRemoteRepoRequest.ProtoReflect.Descriptor instead.
func (*ResolveRemoteRepoRequest) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{9}
}

func (x *ResolveRemoteRepoRequest) GetClientOptions() *ClientOptions {
	if x != nil {
		return x.ClientOptions
	}
	return nil
}

func (x *ResolveRemoteRepoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ResolveRemoteRepoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*ResolveRemoteRepoResponse_Output
	//	*ResolveRemoteRepoResponse_RemoteRepo
	Response isResolveRemoteRepoResponse_Response `protobuf_oneof:"response"`
}

func (x *ResolveRemoteRepoResponse) Reset() {
	*x = ResolveRemoteRepoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveRemoteRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRemoteRepoResponse) ProtoMessage() {}

func (x *ResolveRemoteRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRemoteRepoResponse.ProtoReflect.Descriptor instead.
func (*ResolveRemoteRepoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{10}
}

func (m *ResolveRemoteRepoResponse) GetResponse() isResolveRemoteRepoResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ResolveRemoteRepoResponse) GetOutput() *ClientOutput {
	if x, ok := x.GetResponse().(*ResolveRemoteRepoResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *ResolveRemoteRepoResponse) GetRemoteRepo() *RemoteRepo {
	if x, ok := x.GetResponse().(*ResolveRemoteRepoResponse_RemoteRepo); ok {
		return x.RemoteRepo
	}
	return nil
}

type isResolveRemoteRepoResponse_Response interface {
	isResolveRemoteRepoResponse_Response()
}

type ResolveRemoteRepoResponse_Output struct {
	Output *ClientOutput `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type ResolveRemoteRepoResponse_RemoteRepo struct {
	RemoteRepo *RemoteRepo `protobuf:"bytes,2,opt,name=remote_repo,json=remoteRepo,proto3,oneof"`
}

func (*ResolveRemoteRepoResponse_Output) isResolveRemoteRepoResponse_Response() {}

func (*ResolveRemoteRepoResponse_RemoteRepo) isResolveRemoteRepoResponse_Response() {}

type CloneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientOptions *ClientOptions `protobuf:"bytes,1,opt,name=client_options,json=clientOptions,proto3" json:"client_options,omitempty"`
	Source        string         `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	RepoId        string         `protobuf:"bytes,3,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneRequest.ProtoReflect.Descriptor instead.
func (*CloneRequest) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{11}
}

func (x *CloneRequest) GetClientOptions() *ClientOptions {
	if x != nil {
		return x.ClientOptions
	}
	return nil
}

func (x *CloneRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CloneRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type CloneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*CloneResponse_Output
	//	*CloneResponse_LocalRepo
	Response isCloneResponse_Response `protobuf_oneof:"response"`
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneResponse.ProtoReflect.Descriptor instead.
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{12}
}

func (m *CloneResponse) GetResponse() isCloneResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CloneResponse) GetOutput() *ClientOutput {
	if x, ok := x.GetResponse().(*CloneResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *CloneResponse) GetLocalRepo() *LocalRepo {
	if x, ok := x.GetResponse().(*CloneResponse_LocalRepo); ok {
		return x.LocalRepo
	}
	return nil
}

type isCloneResponse_Response interface {
	isCloneResponse_Response()
}

type CloneResponse_Output struct {
	Output *ClientOutput `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type CloneResponse_LocalRepo struct {
	LocalRepo *LocalRepo `protobuf:"bytes,2,opt,name=local_repo,json=localRepo,proto3,oneof"`
}

func (*CloneResponse_Output) isCloneResponse_Response() {}

func (*CloneResponse_LocalRepo) isCloneResponse_Response() {}

type SuggestRepoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word   string            `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Filter SuggestRepoFilter `protobuf:"varint,2,opt,name=filter,proto3,enum=grit.v2.api.SuggestRepoFilter" json:"filter,omitempty"`
}

func (x *SuggestRepoRequest) Reset() {
	*x = SuggestRepoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRepoRequest) ProtoMessage() {}

func (x *SuggestRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRepoRequest.ProtoReflect.Descriptor instead.
func (*SuggestRepoRequest) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{13}
}

func (x *SuggestRepoRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *SuggestRepoRequest) GetFilter() SuggestRepoFilter {
	if x != nil {
		return x.Filter
	}
	return SuggestRepoFilter_SUGGEST_ANY
}

type SuggestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_gritcli_grit_api_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_github_com_gritcli_grit_api_api_proto_rawDescGZIP(), []int{14}
}

func (x *SuggestResponse) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_github_com_gritcli_grit_api_api_proto protoreflect.FileDescriptor

var file_github_com_gritcli_grit_api_api_proto_rawDesc = []byte{
	0x0a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x69,
	0x74, 0x63, 0x6c, 0x69, 0x2f, 0x67, 0x72, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32,
	0x2e, 0x61, 0x70, 0x69, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x13, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x22, 0x7c, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x62, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x44, 0x69, 0x72, 0x22, 0x83,
	0x01, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x77,
	0x65, 0x62, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x65,
	0x62, 0x55, 0x72, 0x6c, 0x22, 0x73, 0x0a, 0x09, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70,
	0x6f, 0x12, 0x38, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52,
	0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x2c, 0x0a, 0x12, 0x61,
	0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x69,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74,
	0x65, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x44, 0x69, 0x72, 0x22, 0x3b, 0x0a, 0x0d, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6c, 0x6f, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x4c, 0x6f, 0x67, 0x22, 0x43, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x44, 0x65, 0x62, 0x75, 0x67, 0x22, 0x72, 0x0a, 0x17, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x94, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x37, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x48, 0x00, 0x52,
	0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x73, 0x0a, 0x18, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x69,
	0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x98, 0x01, 0x0a, 0x19,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x69, 0x74,
	0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x3a,
	0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x48, 0x00, 0x52, 0x0a,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x0d,
	0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x70, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x48, 0x00,
	0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x12, 0x53, 0x75, 0x67, 0x67, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x36, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0f, 0x53, 0x75, 0x67,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x2a, 0x55, 0x0a, 0x11, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x55, 0x47, 0x47, 0x45,
	0x53, 0x54, 0x5f, 0x41, 0x4e, 0x59, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x55, 0x47, 0x47,
	0x45, 0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x53, 0x55, 0x47, 0x47, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x4d, 0x4f,
	0x54, 0x45, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x02, 0x32, 0xb0, 0x03, 0x0a, 0x03, 0x41, 0x50,
	0x49, 0x12, 0x50, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x12, 0x1f, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x24, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76,
	0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x64, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x25, 0x2e, 0x67, 0x72,
	0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x40, 0x0a, 0x05,
	0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x6c, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4c,
	0x0a, 0x0b, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x1f, 0x2e,
	0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x75, 0x67, 0x67,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x67, 0x72, 0x69, 0x74, 0x2e, 0x76, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x75, 0x67,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x69, 0x74, 0x63,
	0x6c, 0x69, 0x2f, 0x67, 0x72, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_github_com_gritcli_grit_api_api_proto_rawDescOnce sync.Once
	file_github_com_gritcli_grit_api_api_proto_rawDescData = file_github_com_gritcli_grit_api_api_proto_rawDesc
)

func file_github_com_gritcli_grit_api_api_proto_rawDescGZIP() []byte {
	file_github_com_gritcli_grit_api_api_proto_rawDescOnce.Do(func() {
		file_github_com_gritcli_grit_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_gritcli_grit_api_api_proto_rawDescData)
	})
	return file_github_com_gritcli_grit_api_api_proto_rawDescData
}

var file_github_com_gritcli_grit_api_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_gritcli_grit_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_github_com_gritcli_grit_api_api_proto_goTypes = []interface{}{
	(SuggestRepoFilter)(0),            // 0: grit.v2.api.SuggestRepoFilter
	(*ListSourcesRequest)(nil),        // 1: grit.v2.api.ListSourcesRequest
	(*ListSourcesResponse)(nil),       // 2: grit.v2.api.ListSourcesResponse
	(*Source)(nil),                    // 3: grit.v2.api.Source
	(*RemoteRepo)(nil),                // 4: grit.v2.api.RemoteRepo
	(*LocalRepo)(nil),                 // 5: grit.v2.api.LocalRepo
	(*ClientOptions)(nil),             // 6: grit.v2.api.ClientOptions
	(*ClientOutput)(nil),              // 7: grit.v2.api.ClientOutput
	(*ResolveLocalRepoRequest)(nil),   // 8: grit.v2.api.ResolveLocalRepoRequest
	(*ResolveLocalRepoResponse)(nil),  // 9: grit.v2.api.ResolveLocalRepoResponse
	(*ResolveRemoteRepoRequest)(nil),  // 10: grit.v2.api.ResolveRemoteRepoRequest
	(*ResolveRemoteRepoResponse)(nil), // 11: grit.v2.api.ResolveRemoteRepoResponse
	(*CloneRequest)(nil),              // 12: grit.v2.api.CloneRequest
	(*CloneResponse)(nil),             // 13: grit.v2.api.CloneResponse
	(*SuggestRepoRequest)(nil),        // 14: grit.v2.api.SuggestRepoRequest
	(*SuggestResponse)(nil),           // 15: grit.v2.api.SuggestResponse
}
var file_github_com_gritcli_grit_api_api_proto_depIdxs = []int32{
	3,  // 0: grit.v2.api.ListSourcesResponse.sources:type_name -> grit.v2.api.Source
	4,  // 1: grit.v2.api.LocalRepo.remote_repo:type_name -> grit.v2.api.RemoteRepo
	6,  // 2: grit.v2.api.ResolveLocalRepoRequest.client_options:type_name -> grit.v2.api.ClientOptions
	7,  // 3: grit.v2.api.ResolveLocalRepoResponse.output:type_name -> grit.v2.api.ClientOutput
	5,  // 4: grit.v2.api.ResolveLocalRepoResponse.local_repo:type_name -> grit.v2.api.LocalRepo
	6,  // 5: grit.v2.api.ResolveRemoteRepoRequest.client_options:type_name -> grit.v2.api.ClientOptions
	7,  // 6: grit.v2.api.ResolveRemoteRepoResponse.output:type_name -> grit.v2.api.ClientOutput
	4,  // 7: grit.v2.api.ResolveRemoteRepoResponse.remote_repo:type_name -> grit.v2.api.RemoteRepo
	6,  // 8: grit.v2.api.CloneRequest.client_options:type_name -> grit.v2.api.ClientOptions
	7,  // 9: grit.v2.api.CloneResponse.output:type_name -> grit.v2.api.ClientOutput
	5,  // 10: grit.v2.api.CloneResponse.local_repo:type_name -> grit.v2.api.LocalRepo
	0,  // 11: grit.v2.api.SuggestRepoRequest.filter:type_name -> grit.v2.api.SuggestRepoFilter
	1,  // 12: grit.v2.api.API.ListSources:input_type -> grit.v2.api.ListSourcesRequest
	8,  // 13: grit.v2.api.API.ResolveLocalRepo:input_type -> grit.v2.api.ResolveLocalRepoRequest
	10, // 14: grit.v2.api.API.ResolveRemoteRepo:input_type -> grit.v2.api.ResolveRemoteRepoRequest
	12, // 15: grit.v2.api.API.Clone:input_type -> grit.v2.api.CloneRequest
	14, // 16: grit.v2.api.API.SuggestRepo:input_type -> grit.v2.api.SuggestRepoRequest
	2,  // 17: grit.v2.api.API.ListSources:output_type -> grit.v2.api.ListSourcesResponse
	9,  // 18: grit.v2.api.API.ResolveLocalRepo:output_type -> grit.v2.api.ResolveLocalRepoResponse
	11, // 19: grit.v2.api.API.ResolveRemoteRepo:output_type -> grit.v2.api.ResolveRemoteRepoResponse
	13, // 20: grit.v2.api.API.Clone:output_type -> grit.v2.api.CloneResponse
	15, // 21: grit.v2.api.API.SuggestRepo:output_type -> grit.v2.api.SuggestResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_github_com_gritcli_grit_api_api_proto_init() }
func file_github_com_gritcli_grit_api_api_proto_init() {
	if File_github_com_gritcli_grit_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_gritcli_grit_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSourcesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSourcesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteRepo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalRepo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveLocalRepoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveLocalRepoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveRemoteRepoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveRemoteRepoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestRepoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_gritcli_grit_api_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_gritcli_grit_api_api_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ResolveLocalRepoResponse_Output)(nil),
		(*ResolveLocalRepoResponse_LocalRepo)(nil),
	}
	file_github_com_gritcli_grit_api_api_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*ResolveRemoteRepoResponse_Output)(nil),
		(*ResolveRemoteRepoResponse_RemoteRepo)(nil),
	}
	file_github_com_gritcli_grit_api_api_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*CloneResponse_Output)(nil),
		(*CloneResponse_LocalRepo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_gritcli_grit_api_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_gritcli_grit_api_api_proto_goTypes,
		DependencyIndexes: file_github_com_gritcli_grit_api_api_proto_depIdxs,
		EnumInfos:         file_github_com_gritcli_grit_api_api_proto_enumTypes,
		MessageInfos:      file_github_com_gritcli_grit_api_api_proto_msgTypes,
	}.Build()
	File_github_com_gritcli_grit_api_api_proto = out.File
	file_github_com_gritcli_grit_api_api_proto_rawDesc = nil
	file_github_com_gritcli_grit_api_api_proto_goTypes = nil
	file_github_com_gritcli_grit_api_api_proto_depIdxs = nil
}
