name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 14 * * 0

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GRIT_TEST_DEPLOY_KEY }}

      - name: Make
        run: make ci
        env:
          GRIT_INTEGRATION_TEST_GITHUB: "true"
          GRIT_INTEGRATION_TEST_GITHUB_TOKEN: ${{ secrets.GRIT_INTEGRATION_TEST_GITHUB_TOKEN }}

      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v2
